FROM python:3.7.6

RUN mkdir -p /github/workspace

WORKDIR /github/workspace

RUN pip3 install  --upgrade pip  && \
    python3 -m pip install -r ./requirements.txt && \
    python3 -m pip install -r ./requirements_web.txt && \
    pip install mindspore>=1.3.0  && \
    pip install gcastle
